build:
  image: node:7.5.0
  environment:
    - NPM_CONFIG_LOGLEVEL=warn
  commands:
    - npm install
    - npm run bootstrap
    - npm run build
    - npm test
    - npm run docs:dist:gzip

publish:
  s3_sync:
    acl: public-read
    region: "eu-west-1"
    bucket: "backpack.sandbox.aws.skyscnr.com"
    access_key: $$SANDBOX_ACCESS_KEY
    secret_key: $$SANDBOX_SECRET_KEY
    source: dist/
    target: /
    delete: true
    content_encoding:
      ".js": gzip
      ".css": gzip
      ".html": gzip
    cache_control:
      ".js": "public, max-age: 86400"
      ".css": "public, max-age: 86400"
    when:
      branch: sandbox

  s3_sync:
    acl: public-read
    region: "eu-west-1"
    bucket: "backpack.prod.aws.skyscnr.com"
    access_key: $$PROD_ACCESS_KEY
    secret_key: $$PROD_SECRET_KEY
    source: dist/
    target: /
    delete: true
    content_encoding:
      ".js": gzip
      ".css": gzip
      ".html": gzip
    cache_control:
      ".js": "public, max-age: 86400"
      ".css": "public, max-age: 86400"
    when:
      branch: master

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    username: Backpack
    channel: backpack-private
    template: >
      :white_check_mark: Backpack has been successfully built (<http://drone.eu-west-1.prod.aws.skyscanner.local/backpack/backpack/$$BUILD_NUMBER|$$BUILD_NUMBER>).
    when:
      branch: master
      success: true

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    username: Backpack
    channel: backpack-private
    template: >
      <!channel> :x: Backpack failed to build correctly (<http://drone.eu-west-1.prod.aws.skyscanner.local/backpack/backpack/$$BUILD_NUMBER|$$BUILD_NUMBER>).
    when:
      branch: master
      failure: true
