name: Backpack Docs CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo that triggered this action'
        required: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: nvm install
        run: nvm install

      - name: nvm use
        run: nvm use

      - name: Check out submodules
        run: |
          git submodule update --init --recursive
          npm run submodules:pull

      - name: Install deps
        run: |
          nvm use
          npm ci

      - name: Danger
        run: npm run danger
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

      - name: Test
        run: npm test

      - name: Build website (master build)
        run: |
          nvm use
          npm run docs:dist
        if: github.ref == 'refs/heads/master'

      # As above, but with an extra environment variable.
      - name: Build website (pull request build)
        run: |
          nvm use
          npm run docs:dist
        if: github.ref != 'refs/heads/master'
        env:
          BASE_PATH: prs/${{ github.event.pull_request.number }}

      - name: Check site was built correctly
        run: test -e dist/index.html

      - name: Deploy website (master build)
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: dist/
          keep_files: false
          external_repository: backpack/backpack.github.io
          publish_branch: master

      - name: Prepare to deploy (pull request build)
        run: |
          mkdir build
          mv dist $PR_NUMBER
          cp -R $PR_NUMBER build/
        if: github.ref != 'refs/heads/master'
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Deploy website (pull request build)
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref != 'refs/heads/master'
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: build/
          keep_files: true
          external_repository: backpack/prs
          publish_branch: main

      - name: Link to the pull request build
        uses: unsplash/comment-on-pr@master
        if: github.ref != 'refs/heads/master'
        with:
          msg: "Visit https://backpack.github.io/prs/${{ env.PR_NUMBER }} to see this build running in a browser."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
